//TODO CAMBIAR LOS NGMODEL DEPRECATED (INCLUIRLO EN LOS VALORES DEL FORMCONTROL DIRECTAMENTE)

//TODO MODIFICAR EL DISEÑO DEL PERFIL, Y LOS DISEÑOS EN GENERAL

//TODO NO PODER UNIRSE A UNA PARTIDA SI NO ESTA LA SESION INICIADA ==> REDIRIGIR A INICIAR SESION


//TODO Arreglar el this.usuario.id en PERFIL COMPONENT


//TODO VALIDAR FORMULARIO EN PERFIL COMPONENT

//TODO MOSTRAR JUGADORES QUE SE HAN UNIDO A LA PARTIDA (?)