//TODO CAMBIAR LOS NGMODEL DEPRECATED (INCLUIRLO EN LOS VALORES DEL FORMCONTROL DIRECTAMENTE)

//TODO MODIFICAR EL DISEÑO DEL PERFIL, Y LOS DISEÑOS EN GENERAL

//TODO NO PODER UNIRSE A UNA PARTIDA SI NO ESTA LA SESION INICIADA ==> REDIRIGIR A INICIAR SESION [V]


//TODO Arreglar el this.usuario.id en PERFIL COMPONENT [V]


//TODO VALIDAR FORMULARIO EN PERFIL COMPONENT

//TODO MOSTRAR JUGADORES QUE SE HAN UNIDO A LA PARTIDA (?)


//TODO SI YA ESTAS LOGADO , NO PUEDES VOLVER A LOGARTE, PRIMERO CERRAR SESIÓN.

//TODO BOTON DE FOOTER QUE SUBA HACIA ARRIBA




//* ALGUNAS EXPLICACIONES


//* El registro de partida se genera aleatoriamente SOLO al CREAR una partida con el formulario.
//* AL unirse un jugador a la partida se crea un nuevo id y una nueva fila de partida, con el mismo  